version: '3'

services: 
  goiban:
    image: fourcube/openiban
    ports:
      - "12346:8080"
    container_name: goiban
    networks: 
      - goiban
    depends_on: 
      - mysql_goiban

  phpmyadmin_goiban:
    image: phpmyadmin/phpmyadmin:latest
    environment: 
      - PMA_PORT=3306
      - PMA_HOST=mysql_goiban
    ports: 
      - 18080:80
    depends_on: 
      - mysql_goiban
    networks: 
      - goiban

  mysql_goiban:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=goiban
    container_name: mysql_goiban
    networks: 
      - goiban
    volumes: 
      - ./mysql/.docker/build-ressources:/docker-entrypoint-initdb.d

networks:
  goiban: