version: '3.2'

services: 
  goiban:
    image: fourcube/openiban
    ports:
      - "12346:8080"
    container_name: goiban
    restart: unless-stopped
    networks: 
      - goiban
    depends_on: 
      - mysql_goiban

  goiban_data_loader:
    image: onesty/goibandataloader:0.0.1
    container_name: goiban_data_loader
    restart: unless-stopped
    networks: 
      - goiban
    depends_on: 
      - mysql_goiban
    volumes:
      - goiban_data:/data
    environment: 
      - EXCEL_TO_DATABASE_JOB_CRON=0 0/5 * * * ?
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_goiban:3306/goiban
      - EXCEL_FILE_DELETE=false

  phpmyadmin_goiban:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_goiban
    restart: unless-stopped
    environment: 
      - PMA_PORT=3306
      - PMA_HOST=mysql_goiban
    ports: 
      - 38080:80
    depends_on: 
      - mysql_goiban
    networks: 
      - goiban

  mysql_goiban:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=goiban
    container_name: mysql_goiban
    restart: unless-stopped
    networks: 
      - goiban
    volumes: 
      - ./mysql/.docker/build-ressources:/docker-entrypoint-initdb.d

networks:
  goiban:

volumes:
  goiban_data: